### ISSUE TITLE
Can not add Spawn Egg

### ISSUE THREAD

**Issue by jackyjhih** [eylexlive/RandomItemDropper#1]
Hi, 

I got some problem of additem function, I want to add spawn eggs and netherite ingot to the drop item list

but the plugin return it's null item

So this plugin can use only in the material list you post? or how can I do to fix it?

Thanks a lot

**Comment by eylexlive** [comment]
Hello, i never tested spawn eggs, netherite etc.. When im tested 'll fix it

jackyjhih <notifications@github.com>, 21 Ara 2020 Pzt, 17:26 tarihinde şunu
yazdı:

**Comment by eylexlive** [comment]
Hello, I never tested spawn eggs, netherite ingots etc..I'll take a look
when I'm available. Thanks for the report!
